### ISSUE TITLE
Incorrect Compilation for Functions

### ISSUE THREAD

**Issue by airza** [tqbf/jailbreak-trainer#12]
`
  int main() {
  char *p ="qqqqq";
  char* z = decrypt(p);
  printint(1);
  return 0;
}`
is legal, but

`int main() {
  char *p ="qqqqq";
  printint(1);
  char* z = decrypt(p);
  return 0;
}`

fails with error line 13 (at []): Term expected, but got Char.  I am pretty sure this is not correct.

**Comment by Rami114** [comment]
Yeah it looks like you have to declare and initialise variables before you call functions, had the same thing.

**Comment by tqbf** [comment]
Hah, assume this is C89. :)

I definitely won't be fixing this (I lifted/ported the parser from c4, and this is pretty baked into that parser).
