### ISSUE TITLE
Level3 can be used to validate other levels

### ISSUE THREAD

**Issue by philippelaulheret** [tqbf/jailbreak-trainer#24]
Assuming it's not intended; one can call field_unlock in level 3 directly and use it to validate that level and at least the following one.. (hoping I'm not captain obvious and missing the point......)

**Comment by Rami114** [comment]
I don't think the interrupt table aligns the same between those 2 challenges, so not sure how'd that work.

**Comment by tqbf** [comment]
Not sure how exactly that works. What are you passing to field_unlock? Calling field_unlock isn't the challenge in 2 & 3; it's what you pass to it.

**Comment by silverbahamut** [comment]
Sorry I was trying to not be too obvious in case I'd spoil the fun to people looking at issue on github; I guess the bigger problem I was pointing at : starting level 4, I found the name of the level and the verifier then it's possible to go back to level 3, use the field_unlock with the info of level 4; the game says "you've solved challenge 4" and it unlocks level 5.

**Comment by philippelaulheret** [comment]
Sorry I was trying to not be too obvious in case I'd spoil the fun to people looking at issue on github; I guess the bigger problem I was pointing at : starting level 4, I found the name of the level and the verifier then it's possible to go back to level 3, use the field_unlock with the info of level 4; the game says "you've solved challenge 4" and it unlocks level 5.

**Comment by tqbf** [comment]
HAH. Calling this the first real vulnerability found so far. Great work!

**Comment by tqbf** [comment]
Give it a minute and try that trick again?

**Comment by philippelaulheret** [comment]
Looked briefly and says invalid level now (being at work at the moment I don't have a big bandwidth to do some testing). I'll check again around lunch time with one or two more ideas I had that hopefully broke as well :)
