### ISSUE TITLE
runto command doesn't work

### ISSUE THREAD

**Issue by bobjansen** [tqbf/jailbreak-trainer#26]
Entering `runto 0b6a` or any other address and pressing enter doesn't do anything. The input just sits there and the command is not added to history. Just entering `runto` gives usage advice. 

Leigh on Slack helpfully pointed out that the command generates the following JavaScript error:

```
bundle.js:3090 Uncaught TypeError: a.runTo is not a function
```

**Comment by boboTjones** [comment]
Partially fixed. Requires a decimal value to work.

**Comment by tqbf** [comment]
Runto now handles hex offsets and symbols
