### ISSUE TITLE
icall instruction makes weird jump

### ISSUE THREAD

**Issue by airza** [tqbf/jailbreak-trainer#28]
The Icall instruction seems to jump to the right location, but for no obvious reason
per AVR spec it jumps to whatever is in Z.
On level 4, run
`int 
main() {
 printint(4);
 return 0;
}`
and run to the icall at 0x0de4

Z is  43 05 so I expect this to jump to 0x0543. instead it jumps to 0x0a86.  There didn't seem to be any obvious way this could be an offset instead of absolute addressing situation.

**Comment by tqbf** [comment]
Welcome to AVR. Instructions are word-addressed. Multiply jump addresses by 2. :)
