### ISSUE TITLE
Compiler/vm doesn't like nested for loop

### ISSUE THREAD

**Issue by philippelaulheret** [tqbf/jailbreak-trainer#29]
Trying to run this program gives unexpected behavior when i > 8
The inner loop is not executed anymore and i takes bigger values than it supposed limit

```
int bug()
{

    int i;
    int j;
    int nLines;
    nLines = 20;
    for (i = 0; i < nLines; i++)
    {
        for (j = 0; j < 16; j++ )
        {
          printint(j);
        }
        printstring("i");
        printint(i);
        //printstring(buf);

    }

    return 0;

}

int 
main() { 
  bug();
  printstring("actually ran!");
  return 0;
}
```

**Comment by tqbf** [comment]
Yep. It looks like the inner for loop jumps out of the outer for loop when the condition fails. WILL FIX shortly.

**Comment by tqbf** [comment]
All of the nested loops were probably broken, but they should work now (this test program prints the expected output).
