### ISSUE TITLE
Assembler generates same opcodes for pushing different registers

### ISSUE THREAD

**Issue by lt** [tqbf/jailbreak-trainer#37]
``` asm
push r16
push r17
push r28
push r29
```

assembles to

``` C
"\x0f\x92"
"\x0f\x92"
"\x0f\x92"
"\x0f\x92"
```

**Comment by boboTjones** [comment]
Looks like it's defaulting to `PUSH r0`

**Comment by boboTjones** [comment]
There is a bug in the AVR documentation that displays PUSH having the same op as POP. This bug was addressed and documented in the disassembler but not in the assembler. Good catch. Thanks!
