### ISSUE TITLE
Escaping characters in C works, but backslash persists in memory

### ISSUE THREAD

**Issue by Rami114** [tqbf/jailbreak-trainer#4]
Something like ```\"``` in a string literal will work for the compilation of the C, but then ```\"``` will literally be in the memory.

Cosmetic mostly, but the backslash should surely be stripped.

**Comment by Rami114** [comment]
On second thought, this might be completely working as intended...

**Comment by lt** [comment]
Could be the JSON encoder escaping it.

**Comment by tqbf** [comment]
Are you sure about this? I've written pretty decently long chains of both assembly and return sequences using just \x-strings.

Is this specific to \"?

(There shouldn't be any JSON involved in compiling C code; it gets sent as plain text to the compiler endpoint).

**Comment by lt** [comment]
Sorry, I just happened to know from the Slack channel Rami was playing with breaking the JSON at the time, wondered if that's where he was seeing it as `\"` still.

**Comment by Rami114** [comment]
```
int 
main() { 
  printstring("Testing that backslash with \"");

  return 0;
}
```

**Comment by Rami114** [comment]
The above reproduces it

**Comment by tqbf** [comment]
The \" escape should work fine. There are definitely others that don't, but open new bugs for those.
