### ISSUE TITLE
/device/memory/:offset returns wrong last offset

### ISSUE THREAD

**Issue by edsrzf** [tqbf/jailbreak-trainer#46]
Example: (actual bytes in the response omitted for brevity; set JAILBREAK_KEY to your API key)

```
$ curl 'https://www.stockfighter.io/trainer/device/memory/0?hashes=0,0,0' -H "Cookie: api_key=$JAILBREAK_KEY"
{
    "ok": true,
    "segments": [
        {
            "bytes64": "base64 encoded length 29128; decoded length 21845",
            "hash": "0a8199ad",
            "offset": 0
        },
        {
            "bytes64": "base64 encoded length 29128; decoded length 21845",
            "hash": "f5040d75",
            "offset": 21845
        },
        {
            "bytes64": "base64 encoded length 29128; decoded length 21846",
            "hash": "83f4d12d",
            "offset": 65536
        }
    ]
}
```

So here (on level 2), if we add up the sizes of the segments, the total size of memory is 2*21845+21846 = 64K. Because that number can't be evenly divided by 3, the last segment gets the remainder. All good.

However, for some reason the offset of the last segment points to the _end_ of memory, which I'm pretty sure is wrong. I think it should be 2*21845=43690. This happens even if I use 4 hashes, which evenly divides 64K.

On a side note, it would be nice if each segment in this endpoint included its segment number so clients could easily map the segment back to its hash. (I can file a separate issue for this if necessary.)

**Comment by boboTjones** [comment]
Fixed. Segment Number added. Not pushed to production.
