### ISSUE TITLE
Floating help bubble for `r1` is in the wrong position

### ISSUE THREAD

**Issue by zellyn** [tqbf/jailbreak-trainer#48]
![bubble-floating-top-left](https://cloud.githubusercontent.com/assets/33625/15782626/16a9624e-2979-11e6-8e0c-9c316248d344.png)

**Comment by boboTjones** [comment]
I can't repeat this, either. 
<img width="1173" alt="screenshot 2016-06-03 14 30 08" src="https://cloud.githubusercontent.com/assets/28289/15790582/b327fb3a-2997-11e6-9397-8d7ac6b510a1.png">
