### ISSUE TITLE
Completing first level redirects to 404

### ISSUE THREAD

**Issue by zellyn** [tqbf/jailbreak-trainer#49]
Redirects to https://www.stockfighter.io/dox#levels, which says

```
404 File Not Found
```

A 404 error? That's quite unexpected -- we try to make sure once pages get published they stay published. We don't get automatic notifications about this because 99.98% of the time it is caused by a poorly behaving spider or a mangled HTTP request, but if you think there really should be something here, please contact us and we'll fix it.

**Comment by boboTjones** [comment]
This should be  https://www.stockfighter.io/trainer/dox#levels. It's fixed but not pushed to production.
