### ISSUE TITLE
(UI) Memory dump issues

### ISSUE THREAD

**Issue by akrasuski1** [tqbf/jailbreak-trainer#52]
Memdump font should be monospaced. Also, the colored rectangles around SP or Rx positions make the memdump look somewhat misplaced:
![image](https://cloud.githubusercontent.com/assets/5507813/15783571/fd8154da-29ae-11e6-9600-c1eef36081f0.png)

The break between 4th and 5th columns from the right is wider than most of them, for instance.

**Comment by boboTjones** [comment]
I was in the process of fixing this -- what browser are you using? That font is definitely not correct.

**Comment by akrasuski1** [comment]
Chromium 
Version 50.0.2661.102 Ubuntu 16.04 (64-bit)

**Comment by boboTjones** [comment]
https://www.dropbox.com/s/m35ylp9blf9ksok/Screenshot%202016-06-03%2013.15.10.png
