### ISSUE TITLE
Breakpoint API semantics

### ISSUE THREAD

**Issue by lt** [tqbf/jailbreak-trainer#65]
I think the breakpoint API endpoints are bit off semantically

```
GET    /device/breakpoints
PUT    /device/breakpoints/:offset
DELETE /device/breakpoint/:offset
POST   /device/breakpoints/:number/expression
```

The GET is fine, however the others should be:

```
POST   /device/breakpoints/:offset
DELETE /device/breakpoint/:number
PUT    /device/breakpoint/:number/:expression
```

POST to add to the breakpoint pool. You can add multiple breakpoints for the same offset (with different conditions), so a PUT doesn't make sense here. (Also gives a little more use to the numbering system)

DELETE should take a numbered breakpoint rather than an offset. At the moment this also causes an issue where if you delete one breakpoint for a particular offset, all breakpoints for that offset are removed.

PUT should be used to set the condition on a numbered breakpoint

I believe this one is just a doc issue, and is a POST already in reality

```
GET /vm/write
```

**Comment by boboTjones** [comment]
Fixed.
