### ISSUE TITLE
(Docs) Retrieve Device Status missing pc_string field

### ISSUE THREAD

**Issue by knisbet** [tqbf/jailbreak-trainer#67]
Title: (Docs) Retrieve Device Status missing pc_string field
Severity: Minor
User Impact: Miss-interpretation of documentation
API: /jailbreak/device/status

Summary:
  There appears to be a discrepency in the readme.io vs. the actual API results. The readme.io documentation appears to be missing the field pc_string

Details:
  The actual API returns the following API results on a running level.

Results from the API:

```
{
  "ok": true,
  "address": "XgXzBhOtZVzQwxoQ7EGz3Ih9aYnamdT7dR4Osexk",
  "runcount": 1,
  "apu_state": {
    "pc": 2510,
    "sp": "ef7c",
    "sr": 63,
    "sr_string": "IthsvnZc",
    "pc_string": "09ce",
    "cycles": 115638,
<snip>
```

The result format for 200 OK from readme.io:

```
{
    "ok": true,
    "address": "Um1uAxLDpeyxNsHnoIq4oKCjGsNnPf45WhXsa4Gr",
    "runcount": 1,
    "apu_state": {
        "pc": 0,
        "sp": "0000",
        "sr": 63,
        "sr_string": "ithsvnzc",
        "cycles": 0,
<snip>
```

The readme.io docs appear to overlook this field, both in the example results for 200OK, and the table of field descriptions.

**Comment by boboTjones** [comment]
fixed
