### ISSUE TITLE
/device/program/apu contains unicode < and > characters in symbol field

### ISSUE THREAD

**Issue by knisbet** [tqbf/jailbreak-trainer#68]
Title: /device/program/apu contains unicode < and > characters in symbol field
Severity: Minor
User Impact: May make API results harder to process / interpret
API: /device/program/apu

Summary:
  I've encountered unicode characters in the JSON results of the API. While normally I wouldn't consider this a problem, it is something that may create unnecessary burden for processing the text.

Details:
So I noticed this, because it turns out the rust language json decoder I'm using apparently doesn't have support for unicode characters in the json strings. While ultimately I'd say this is a problem with the rust decoder, to me it seems like one of those things that having the unicode characters are unnecessary.

Example line:
"symbol": "3cce\t\u003c_exit\u003e:

In this case, the unicode escapes are meant to indicate 3cce    \t<c_exit>

Anyways, I thought I'd let you know.

**Comment by boboTjones** [comment]
From the docs: 

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. The angle brackets "<" and ">" are escaped to "\u003c" and "\u003e" to keep some browsers from misinterpreting JSON output as HTML. Ampersand "&" is also escaped to "\u0026" for the same reason.
