### ISSUE TITLE
(Docs) dox debugger command reference contains show command twice

### ISSUE THREAD

**Issue by knisbet** [tqbf/jailbreak-trainer#69]
Title: (Docs) dox debugger command reference contains show command twice
Severity: Minor
User Impact: None

Summary:
  This is just a minor documentation issue, the page https://www.stockfighter.io/trainer/dox#debugger for the command reference, contains the show command twice with slightly different definitions.

Details:

Definition 1:
show show efbf
Highlight an address in the disassembly.

Defintion 2:
show show efbf
Highlight the specified instruction in the disassembly.

**Comment by boboTjones** [comment]
fixed
