### ISSUE TITLE
Issues with r/X commands returning undefined for literal addresses

### ISSUE THREAD

**Issue by queenp** [tqbf/jailbreak-trainer#76]
r/8 01b0 (location for a known non-zero ascii data)
produces

   8 bits at address 01b0
   decimal: NaN
   hex: 0NaN
   binary: NaN

r/16, r/32 and r/s do similar things with slightly different error messages.

(on browser: Chrome 49.0.2623.87 (Official Build) (64-bit))

r/N [addr] returns "{number_of_bits}bits from undefined...".

**Comment by tqbf** [comment]
Thanks so much for this. Dumb bug; I refactored the command line to add inline help, and forgot to rename some variables.

**Comment by queenp** [comment]
Still experiencing this bug.

Messing around with it more, seems like: `r/? 02d0` is returning a value from `r0` (or an error depending on the read format).

For instance `r/32 r28` reads the long starting at at 001c, `r/32 001c` returns the value of r0, or `r/32 [001c]` returns -1 bites from rundefined.

**Comment by tqbf** [comment]
It's possible you were seeing that because the deploy I ran failed (and then I got sick and didn't do any work for a couple days). If it's not fixed now (that I've watched a deploy succeed) I will whack on it until it is.
