### ISSUE TITLE
Initial compiler output

### ISSUE THREAD

**Issue by lt** [tqbf/jailbreak-trainer#9]
This was intentional
-spoiler removed-

**Comment by tqbf** [comment]
The compile window will compile periodically, just to be helpful. I should make it less helpful.

**Comment by lt** [comment]
I was referring more to all of the UNDEF spam, the actual disasm is right at the bottom, but there's a lot of "stuff" above it that should probably be hidden away

**Comment by lt** [comment]
Closing now I know what the junk is
